// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9_gsihVoe5otK16zcjKYoDegwT_0lmrg',
    appId: '1:144208948409:web:a592ed9367571a422bff68',
    messagingSenderId: '144208948409',
    projectId: 'chatkro-7fd82',
    authDomain: 'chatkro-7fd82.firebaseapp.com',
    storageBucket: 'chatkro-7fd82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB2zeBkP3FeudpGceqm_Z7PN9SwmFUEgE',
    appId: '1:144208948409:android:c8b26fb2173672232bff68',
    messagingSenderId: '144208948409',
    projectId: 'chatkro-7fd82',
    storageBucket: 'chatkro-7fd82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqlm-4rAPT4rYnha66v9RxCO4odNsY6X0',
    appId: '1:144208948409:ios:eee98ae7e4ab59012bff68',
    messagingSenderId: '144208948409',
    projectId: 'chatkro-7fd82',
    storageBucket: 'chatkro-7fd82.appspot.com',
    iosBundleId: 'com.example.chatkro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqlm-4rAPT4rYnha66v9RxCO4odNsY6X0',
    appId: '1:144208948409:ios:eee98ae7e4ab59012bff68',
    messagingSenderId: '144208948409',
    projectId: 'chatkro-7fd82',
    storageBucket: 'chatkro-7fd82.appspot.com',
    iosBundleId: 'com.example.chatkro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9_gsihVoe5otK16zcjKYoDegwT_0lmrg',
    appId: '1:144208948409:web:e9583f506f2f41e82bff68',
    messagingSenderId: '144208948409',
    projectId: 'chatkro-7fd82',
    authDomain: 'chatkro-7fd82.firebaseapp.com',
    storageBucket: 'chatkro-7fd82.appspot.com',
  );
}
